### ISSUE TITLE
errorMessage is not a standard keyword in the JSON Schema specification, hence linting fails

### ISSUE THREAD

**Issue by kesavab** [ajv-validator/ajv-errors#152]
Hello there,

When I add this key value pair to already valid api spec, my linting fails. 

I used pet store spec and added this errorMessage and below is the screenshot from the Swagger Editor. 

![image](https://github.com/ajv-validator/ajv-errors/assets/12221481/4cb78b2e-c6f9-4e6f-a618-9a8c95efa2ce)

This is the error from Spectral linting.

![image](https://github.com/ajv-validator/ajv-errors/assets/12221481/857acca1-facf-4ec6-9929-57a5c82d0a19)

Kindly let me know how we can fix this linting errors.

**Comment by epoberezkin** [comment]
This is the question to the linter library - how to extend allowed keywords - not to this library, sorry.
