### ISSUE TITLE
How to use it in TypeScript import

### ISSUE THREAD

**Issue by nandhu** [ajv-validator/ajv-errors#63]
Hi,
I want to use ajv errors in JSONforms react(typescript) app. I have defined the errorMessage in the schema. But it always showing the generated messages instead of custom messages
`import Ajv from 'ajv';
import AjvErrors from 'ajv-errors';
const ajv = new Ajv({ allErrors: true, jsonPointers: true });
const AjvConfig = AjvErrors(ajv);

export default AjvConfig;`

Thanks

**Comment by paul-uz** [comment]
@nandhu did you figure this out?
