### ISSUE TITLE
TypeError: ajv_1.Name is not a constructor

### ISSUE THREAD

**Issue by YuDaChao** [ajv-validator/ajv-errors#77]
"ajv": "^7.0.0-beta.4",
"ajv-errors": "^2.0.0-beta.0",

const ajv = new Ajv({ allErrors: true })
require('ajv-errors')(ajv)

**Comment by epoberezkin** [comment]
These versions are not compatible, you need the latest Ajv beta (.7)

**Comment by epoberezkin** [comment]
https://github.com/ajv-validator/ajv/releases/tag/v7.0.0-beta.7
